name: 'Publish'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    
    name: 'Deploy to Netlify'
    steps:
      - uses: actions/checkout@v2
    
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "."
          #pre-build-command: "pip install sphinx_rtd_theme && pip install sphinx-notfound-page"
          build-command: "sphinx-build -b html . _build"
    
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './_build'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
